feature/criu/image.inc: respect COMPATIBLE_HOST when install
Issue: LIN9-2354

The criu sets COMPATIBLE_HOST to x86_64, but no x86, so there would be
errors when build with multilib, use
IMAGE_INSTALL_append_x86-64 = "criu" doesn't work either since
multilib.bbclass doesn't change DEFAULTTUNE for image recipe, and it's
the way the system is designed, so use a function to fix the problem,
and it can be removed once criu supports both x86_64 and x86.

Fixed:
$ setup.sh --machines qemux86-64 --template feature/criu
$ bitbake wrlinux-image-glibc-std

ERROR: lib32-criu was skipped: incompatible with host i686-wrsmllib32-linux (not in COMPATIBLE_HOST)
NOTE: Runtime target 'lib32-criu' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-criu']
ERROR: Required build target 'wrlinux-image-glibc-std' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-glibc-std', 'lib32-wrlinux-image-glibc-std', 'lib32-criu']

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>