classes/kernel-windriver.bbclass: remove wrlcompat related code
Issue: LIN9-1903

They were used for creating symlinks in export dir, now they are not
needed any more. And they caused errors when
"bitbake <image> -c populate_sdk_ext":
ERROR: Task linux-windriver.do_deploy_post attempted to execute unexpectedly

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>