hwdata: use github instead of slackware
Issue: LIN9-5617

Fixes:
ERROR: hwdata-0.291-r0 do_fetch: Fetcher failure for URL:
'http://ftp.slackware.com/pub/slackware/slackware-current/source/a/hwdata/hwdata-0.291.tar.xz&#39;.
Unable to fetch URL from any source.

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>