wrlinux-image-initramfs: depends on grub-efi:do_populate_lic
Issue: LIN9-4712

Make sure grub-efi:do_populate_lic has been done before running the
do_image_complete. This fixes error:

  Exception: FileNotFoundError: [Errno 2] No such file or directory: \
    '.../tmp/deploy/licenses/grub-efi/recipeinfo'
  ERROR: wrlinux-image-initramfs-1.0-r0 do_image_complete: \
    Function failed: write_deploy_manifest

Signed-off-by: Wenzong Fan <wenzong.fan@windriver.com>