kdump: drop makedumpfile for aarch64
Currently aarch64 is not supported by makedumpfile, so explicitly remove it
from template to avoid the following build error:

Parsing recipes: 100% |#############################################################################################################################################################################| Time: 0:00:46
Parsing of 2123 .bb files complete (0 cached, 2123 parsed). 4983 targets, 2500 skipped, 11 masked, 0 errors.
NOTE: Resolving any missing task queue dependencies
ERROR: Nothing RPROVIDES 'makedumpfile' (but wrlinux-image-glibc-std.bb RDEPENDS on or otherwise requires it)
ERROR: makedumpfile was skipped: incompatible with host aarch64-wrs-linux (not in COMPATIBLE_HOST)
NOTE: Runtime target 'makedumpfile' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['makedumpfile']
NOTE: Runtime target 'lib32-wrlinux-image-glibc-std' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['lib32-wrlinux-image-glibc-std', 'wrlinux-image-glibc-std', 'makedumpfile']
ERROR: Required build target 'wrlinux-image-glibc-std' has no buildable providers.
Missing or unbuildable dependency chain was: ['wrlinux-image-glibc-std', 'makedumpfile']

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>