intel-x86: fix build error led by iwlwifi-8265-21.ucode firmware
Issue: LIN9-2362

Fix the following build error:
error: Can't install linux-firmware-iwlwifi-1:0.0+git0+42ad5367dd-r0@all: no
package provides linux-firmware-iwlwifi-8265

This is because the 8265-21.ucode and 8265-22.ucode was spilit to different
package which named linux-firmware-iwlwifi-8265-21 and linux-firmware-iwlwifi-8265-22
It cause the package linux-firmware-iwlwifi-8265 was NULL, so got the build error.

To fix it just Install linux-firmware-iwlwifi-8265 which already provided in oe-core,
and drop the package maker action in recipe-kernel/linux-firmware

Signed-off-by: Liwei Song <liwei.song@windriver.com>