linux-libc-headers-windriver: add RPROVIDES for linux-libc-headers-windriver-dev
Issue: LIN9-8168

linux-libc-headers-dev has been added to RDEPENDS in commit
<Add linux-libc-headers-dev into sdk-target> for oe-core. But when
setting:
PREFERRED_PROVIDER_linux-libc-headers = "linux-libc-headers-windriver",
there will be such error reported when populate_sdk with the above
provider setting:
ERROR: Multiple .bb files are due to be built which each provide linux-libc-headers:
  .../layers/oe-core/meta/recipes-kernel/linux-libc-headers/linux-libc-headers_4.8.bb
  .../layers/wr-kernel/kernel-dev/recipes-kernel/linux-libc-headers/linux-libc-headers-windriver.bb

Here add RPROVIDES for linux-libc-headers-windriver-dev to make
linux-libc-headers-dev provided by linux-libc-headers-windriver.bb
in such case.

(LOCAL REV: NOT UPSTREAM) -- Not Applicable

Signed-off-by: Li Zhou <li.zhou@windriver.com>