Revert "wr-kernel/intel-pcm: fix No GUN_HASH in the elf binary QA warning"
This reverts commit eeeb3605a4de455ef92d99614db0c648eef3d89a.
The required patch was not added so the builds were failing with:
   ERROR: Fetcher failure for URL: 'file://0001-wr-kernel-intel-pcm-fix-No-GNU_HASH-in-the-elf-binar.patch'. Unable to fetch URL from any source.