kernel-dev/default/template.conf: conditionally set TOOLCHAIN_TARGET_TASK_append
Issue: LIN9-2287

Fixed when kernel-dev layer is enaled:
$ bitbake uninative-tarball/buildtools-tarball
[snip]
ERROR: uninative-tarball-1.0-r0 do_populate_sdk: python-dev not found in the feeds () in /buildarea/lyang1/test_a/tmp/deploy/rpm.
ERROR: uninative-tarball-1.0-r0 do_populate_sdk: Function failed: do_populate_sdk
[snip]

The uninative-tarball and buildtools-tarball doesn't need any target recipes.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>